const ROLES = {
  PATIENT: "patient",
  DOCTOR: "doctor",
  ADMIN: "admin",
};

const SESSIONS = ["morning", "afternoon"];

const APPOINTMENT_STATUS = {
  BOOKED: "booked",
  WAITING: "waiting",
  CALLED: "called",
  IN_CONSULTATION: "in_consultation",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  NO_SHOW: "no_show",
};

const ACTIVE_FOR_QUOTA = [
  APPOINTMENT_STATUS.BOOKED,
  APPOINTMENT_STATUS.WAITING,
  APPOINTMENT_STATUS.CALLED,
  APPOINTMENT_STATUS.IN_CONSULTATION,
  APPOINTMENT_STATUS.COMPLETED,
  APPOINTMENT_STATUS.NO_SHOW,
];

const ACTIVE_FOR_DOUBLE_BOOK = [
  APPOINTMENT_STATUS.BOOKED,
  APPOINTMENT_STATUS.WAITING,
  APPOINTMENT_STATUS.CALLED,
  APPOINTMENT_STATUS.IN_CONSULTATION,
  APPOINTMENT_STATUS.COMPLETED,
];

const SESSION_STARTED_STATUSES = [
  APPOINTMENT_STATUS.WAITING,
  APPOINTMENT_STATUS.CALLED,
  APPOINTMENT_STATUS.IN_CONSULTATION,
  APPOINTMENT_STATUS.COMPLETED,
  APPOINTMENT_STATUS.NO_SHOW,
];

const BUSY_STATUSES = [
  APPOINTMENT_STATUS.CALLED,
  APPOINTMENT_STATUS.IN_CONSULTATION,
];

const BOARD_STATUSES = [
  APPOINTMENT_STATUS.BOOKED,
  APPOINTMENT_STATUS.WAITING,
  APPOINTMENT_STATUS.CALLED,
  APPOINTMENT_STATUS.IN_CONSULTATION,
  APPOINTMENT_STATUS.COMPLETED,
  APPOINTMENT_STATUS.NO_SHOW,
];

const INVOICE_STATUS = {
  UNPAID: "unpaid",
  PENDING: "pending",
  PAID: "paid",
  EXPIRE: "expire",
  FAILED: "failed",
};

const CHAT_WRITABLE_STATUSES = [APPOINTMENT_STATUS.COMPLETED];

const NOTIFICATION_TYPES = {
  QUEUE_CALLED: "queue_called",
  QUEUE_SKIPPED: "queue_skipped",
  SESSION_OPENED: "session_opened",
  APPOINTMENT_CANCELLED: "appointment_cancelled",
  BOOKING_CREATED: "booking_created",
  INVOICE_CREATED: "invoice_created",
  INVOICE_PAID: "invoice_paid",
  INVOICE_FAILED: "invoice_failed",
  INVOICE_EXPIRED: "invoice_expired",
};

module.exports = {
  ROLES,
  SESSIONS,
  APPOINTMENT_STATUS,
  ACTIVE_FOR_QUOTA,
  ACTIVE_FOR_DOUBLE_BOOK,
  SESSION_STARTED_STATUSES,
  BUSY_STATUSES,
  BOARD_STATUSES,
  INVOICE_STATUS,
  CHAT_WRITABLE_STATUSES,
  NOTIFICATION_TYPES,
};
